apiVersion: apps/v1
kind: Deployment
metadata:
  name: teach-deployment
  labels:
     app: teach

spec:
  replicas: 2
  selector:
    matchLabels:
      app: teach

  template:
    metadata:
      labels:
        app: teach
    spec:
      containers:
      - name: teach
        image: devopscentraltest/teachingimage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
